server:
  error:
    include-message: always
spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    url: jdbc:mysql://localhost:3306/public
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
