server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/public
    username: root
    password: password123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
